[package]
name = "movable_type_to_markdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
chrono = "0.4.19"
clap = "3.1.18"
html_parser = "0.6.3"
nom = "7.1.1"
